---
 inventory:
     plugin: SimpleInventory
     options:
         host_file: "inventory/hosts.yaml"
         group_file: "inventory/groups.yaml"
         defaults_file: "inventory/defaults.yaml"
 runner:
     plugin: threaded
     options:
         num_workers: 5





#---
#core:
#  num_workers: 100
#
#inventory:
#  plugin: nornir.plugins.inventory.simple.SimpleInventory
#  options:
#    host_file: "inventory/hosts.yaml"
#    group_file: "inventory/groups.yaml"
#    defaults_file: "inventory/defaults.yaml"
